import { Question, UserProgress } from "./types";

// Sample questions shown in the app. These mirror rows in
// supabase/seed_questions.sql — ids and answer keys match that seed.
export const mockQuestions: Question[] = [
  {
    id: "q1",
    seedId: "fbm-001",
    subject: "Forest Biometrics & Mensuration",
    difficulty: "Medium",
    question: "A standing dipterocarp has a DBH of 60 cm and a merchantable height of 18 m. Using V = (π/4) × D² × H × F with a form factor of 0.70, what is its approximate merchantable volume?",
    options: [
      { id: "a", text: "5.09 m³" },
      { id: "b", text: "2.49 m³" },
      { id: "c", text: "3.56 m³" },
      { id: "d", text: "7.27 m³" },
    ],
    correctAnswerId: "c",
    explanation: "Basal area = (π/4) × (0.60 m)² = 0.2827 m². Volume = 0.2827 × 18 m × 0.70 = 3.56 m³.",
    detailedExplanation: "Step 1: Convert DBH to meters.\n• 60 cm = 0.60 m\n\nStep 2: Compute basal area.\n• BA = (π/4) × D² = 0.7854 × 0.36 = 0.2827 m²\n\nStep 3: Multiply by height and form factor.\n• V = 0.2827 × 18 × 0.70 = 3.562 m³\n\nThe form factor corrects for taper — a tree bole is not a perfect cylinder. A form factor of 0.70 means the tree holds about 70% of the volume of a cylinder of the same DBH and height.\n\nDistractors: 5.09 m³ omits the form factor; 2.49 m³ uses 0.49; 7.27 m³ mistakes 0.60 m for the radius.",
    tips: "Memorize BA = 0.7854 × D² for D in meters, and always convert DBH from centimeters first. That conversion causes more errors than the formula.",
  },
  {
    id: "q2",
    seedId: "sil-002",
    subject: "Silviculture & Forest Ecology",
    difficulty: "Hard",
    question: "Which succession process describes the colonization of a bare lahar deposit or newly cooled lava flow where no soil or seed bank exists?",
    options: [
      { id: "a", text: "Secondary succession" },
      { id: "b", text: "Primary succession" },
      { id: "c", text: "Retrogressive succession" },
      { id: "d", text: "Cyclic succession" },
    ],
    correctAnswerId: "b",
    explanation: "Primary succession occurs on substrates that have never supported vegetation and contain no soil or seed bank — lava flows, lahar deposits, and newly exposed rock.",
    detailedExplanation: "PRIMARY SUCCESSION begins on sterile substrate:\n• No soil, no seed bank, no organic matter.\n• Pioneer colonizers are lichens, mosses, and nitrogen-fixing species.\n• Soil must be built from scratch — a process taking centuries.\n• Philippine example: the lahar fields of Pinatubo.\n\nSECONDARY SUCCESSION begins after a disturbance that removes vegetation but LEAVES THE SOIL INTACT:\n• Soil, seed bank, and root systems survive.\n• Recovery takes decades rather than centuries.\n• Philippine example: abandoned kaingin plots recovering through cogon, then Trema and Macaranga.\n\nThe deciding question is always: DOES SOIL REMAIN?",
    tips: "One diagnostic question separates these: is there soil to start with? Lava, lahar, and bare rock mean primary. Fire, kaingin, and logging mean secondary.",
  },
  {
    id: "q3",
    seedId: "sfp-001",
    subject: "Social Forestry & Forest Policy",
    difficulty: "Easy",
    question: "Under Presidential Decree No. 705 (Revised Forestry Reform Code of the Philippines), lands with a slope of what percentage or more are classified as permanent forest or forest reserves and may not be released for agriculture?",
    options: [
      { id: "a", text: "18% and above" },
      { id: "b", text: "25% and above" },
      { id: "c", text: "50% and above" },
      { id: "d", text: "12% and above" },
    ],
    correctAnswerId: "a",
    explanation: "PD 705 sets the 18% slope line: land 18% in slope or steeper is classified as permanent forest and cannot be released for agricultural purposes.",
    detailedExplanation: "PD 705 (1975) is the foundational forestry statute of the Philippines, and the 18% slope rule is among its most heavily tested provisions.\n\nKey provisions:\n• Lands 18% in slope or above — permanent forest / forest reserve, not alienable and disposable.\n• Lands below 18% slope — may be classified as alienable and disposable after proper survey and land classification.\n• Exception: lands already covered by titles or approved public land applications before the decree.\n• Lands 50% in slope or above, and mossy forests above 1,000 m elevation — declared needing strict protection.\n\nThe rationale is erosion control. Steep slopes cleared for cultivation lose topsoil rapidly, silt downstream waterways, and trigger landslides.",
    tips: "Fix three numbers for PD 705: 18% slope, 50% slope, 1,000 m elevation. They appear in nearly every board exam.",
  },
  {
    id: "q4",
    seedId: "wsf-001",
    subject: "Wood Science & Forest Products",
    difficulty: "Medium",
    question: "What is the fiber saturation point (FSP) of most wood species, and what happens to the wood below this moisture content?",
    options: [
      { id: "a", text: "Around 12% MC; the wood begins to absorb free water" },
      { id: "b", text: "Around 30% MC; the wood begins to swell and lose strength" },
      { id: "c", text: "Around 30% MC; the wood begins to shrink and gain strength" },
      { id: "d", text: "Around 50% MC; dimensional change stops entirely" },
    ],
    correctAnswerId: "c",
    explanation: "The fiber saturation point is approximately 30% moisture content. Below the FSP, bound water leaves the cell walls, causing the wood to shrink and its strength properties to increase.",
    detailedExplanation: "Wood holds moisture in two forms:\n• FREE WATER — liquid water in the cell lumens.\n• BOUND WATER — water chemically held within the cell walls.\n\nThe FIBER SATURATION POINT (~30% MC, varying 28–32% by species) is where all free water has evaporated but the cell walls remain fully saturated.\n\nAbove FSP:\n• Only free water is lost.\n• No dimensional change.\n• No change in mechanical strength.\n\nBelow FSP:\n• Bound water leaves the cell walls.\n• The wood SHRINKS.\n• Strength properties INCREASE.\n\nThis is why lumber must be seasoned to its equilibrium moisture content (about 12–15% in the Philippines) before use — all shrinkage and warping happens below the FSP.",
    tips: "Remember: 'Above FSP, nothing changes; below FSP, everything changes.' Shrinkage and strength gain both begin only after crossing 30% MC going down.",
  },
  {
    id: "q5",
    seedId: "fes-001",
    subject: "Forest Engineering & Surveying",
    difficulty: "Medium",
    question: "In a closed compass traverse, the sum of the interior angles of a five-sided (pentagon) boundary should equal:",
    options: [
      { id: "a", text: "540°" },
      { id: "b", text: "360°" },
      { id: "c", text: "720°" },
      { id: "d", text: "900°" },
    ],
    correctAnswerId: "a",
    explanation: "The sum of interior angles of any closed polygon is (n − 2) × 180°. For n = 5: (5 − 2) × 180° = 540°.",
    detailedExplanation: "The interior angle check is the first thing a forester does when closing a traverse around a forest boundary or plantation block.\n\nFormula: Σ interior angles = (n − 2) × 180°\n\n• Triangle (n=3): 180°\n• Quadrilateral (n=4): 360°\n• Pentagon (n=5): 540°\n• Hexagon (n=6): 720°\n\nThe companion formula for EXTERIOR angles is Σ = (n + 2) × 180°.\n\nIn practice, measured angles will not sum exactly to the theoretical value. The difference is the ANGULAR ERROR OF CLOSURE, distributed equally among stations before computing latitudes and departures. If the error exceeds the allowable limit for the survey class, the traverse must be re-run.",
    tips: "Do not memorize per-shape values — memorize (n − 2) × 180° and derive. The exterior counterpart is (n + 2) × 180°, a favorite distractor.",
  },
  {
    id: "q6",
    seedId: "frm-001",
    subject: "Forest Resources Management",
    difficulty: "Hard",
    question: "A 400-hectare plantation is managed on a 25-year rotation under the area control method. How many hectares should be harvested annually to achieve a sustained yield?",
    options: [
      { id: "a", text: "25 hectares" },
      { id: "b", text: "40 hectares" },
      { id: "c", text: "16 hectares" },
      { id: "d", text: "10 hectares" },
    ],
    correctAnswerId: "c",
    explanation: "Under area control, annual coupe = total area ÷ rotation age = 400 ha ÷ 25 years = 16 hectares per year.",
    detailedExplanation: "AREA CONTROL is the simplest method of regulating a forest for sustained yield. The principle: harvest an equal area each year so that by the end of one rotation, the entire forest has been cut once and the first-cut area is mature again.\n\nFormula: Annual coupe = Total productive area ÷ Rotation age\n• 400 ha ÷ 25 yr = 16 ha/yr\n\nVerification: 16 ha/yr × 25 yr = 400 ha — the whole forest, exactly once. The stand cut in year 1 is 25 years old again in year 26. This is a NORMAL FOREST: equal areas in every age class.\n\nContrast with VOLUME CONTROL, which regulates by cubic meters removed and suits uneven-aged stands.\n\nWhy the distractors are wrong:\n• 25 ha confuses the rotation age with the answer.\n• 40 ha divides by 10 instead of 25.\n• 10 ha divides 400 by 40.",
    tips: "Area control is always area ÷ rotation — never area × rotation. Sanity-check by multiplying back: annual coupe × rotation must return the total area.",
  },
  {
    id: "q7",
    seedId: "sil-007",
    subject: "Silviculture & Forest Ecology",
    difficulty: "Easy",
    question: "Which forest formation in the Philippines is characterized by trees with stilt and pneumatophore roots growing in saline intertidal zones?",
    options: [
      { id: "a", text: "Mossy forest" },
      { id: "b", text: "Molave forest" },
      { id: "c", text: "Mangrove forest" },
      { id: "d", text: "Pine forest" },
    ],
    correctAnswerId: "c",
    explanation: "Mangrove forests occupy saline intertidal zones and are distinguished by specialized aerial roots — stilt roots (Rhizophora) and pneumatophores (Avicennia, Sonneratia).",
    detailedExplanation: "Major Philippine forest formations:\n\n• MANGROVE — intertidal, saline. Stilt roots and pneumatophores handle waterlogged, oxygen-poor soil. Genera: Rhizophora (bakhaw), Avicennia (api-api), Sonneratia (pagatpat), Nypa (sasa). Critical for coastal protection and fishery nurseries.\n\n• BEACH FOREST — above the high tide line on sandy shores. Talisay, Botong, Agoho.\n\n• DIPTEROCARP FOREST — the main timber-producing formation, lowland to 1,000 m. Lauan, Apitong, Yakal, Guijo.\n\n• MOLAVE FOREST — drier limestone areas with a pronounced dry season. Molave, Narra, Ipil.\n\n• PINE FOREST — high elevations of northern Luzon. Benguet pine (Pinus kesiya), Mindoro pine (Pinus merkusii).\n\n• MOSSY FOREST — above roughly 1,000 m, stunted trees heavily draped in mosses and epiphytes. Vital watershed function.",
    tips: "Match the diagnostic root or habitat to the formation. Pneumatophores and stilt roots mean mangrove; stunted trees covered in moss at high elevation mean mossy forest.",
  },
  {
    id: "q8",
    seedId: "wsf-002",
    subject: "Wood Science & Forest Products",
    difficulty: "Easy",
    question: "Which part of the tree trunk consists of dead cells that no longer conduct sap but provide structural support and are typically darker in color?",
    options: [
      { id: "a", text: "Sapwood" },
      { id: "b", text: "Cambium" },
      { id: "c", text: "Phloem" },
      { id: "d", text: "Heartwood" },
    ],
    correctAnswerId: "d",
    explanation: "Heartwood is the inner, darker core of dead cells that has ceased conducting sap. It provides mechanical support and is usually more durable due to accumulated extractives.",
    detailedExplanation: "From the outside of the trunk inward:\n\n1. BARK — outer protective layer.\n2. PHLOEM (inner bark) — conducts food DOWNWARD from the leaves.\n3. CAMBIUM — a single layer of living, dividing cells producing phloem outward and xylem inward. All diameter growth happens here.\n4. SAPWOOD (outer xylem) — living, lighter, conducts water and minerals UPWARD.\n5. HEARTWOOD (inner xylem) — dead cells, darker, no longer conducts sap. Extractives (tannins, resins, oils) make it resistant to decay and insects.\n\nThis is why heartwood commands a higher price: narra, molave, and yakal heartwood are prized for the durability those extractives provide.",
    tips: "Girdling kills a tree because it severs the phloem and cambium — not the heartwood, which is already dead. Exams love this connection.",
  },
  {
    id: "q9",
    seedId: "sfp-002",
    subject: "Social Forestry & Forest Policy",
    difficulty: "Medium",
    question: "What is the tenurial instrument issued by the DENR to organized upland communities under the Community-Based Forest Management (CBFM) Program?",
    options: [
      { id: "a", text: "Timber License Agreement (TLA)" },
      { id: "b", text: "Community-Based Forest Management Agreement (CBFMA)" },
      { id: "c", text: "Integrated Forest Management Agreement (IFMA)" },
      { id: "d", text: "Certificate of Ancestral Domain Title (CADT)" },
    ],
    correctAnswerId: "b",
    explanation: "The CBFMA is a 25-year, renewable-for-another-25-years production-sharing agreement between the DENR and an organized upland community (a People's Organization).",
    detailedExplanation: "Executive Order No. 263 (1995) adopted CBFM as the national strategy for sustainable forestry and social justice in the uplands.\n\nCBFMA essentials:\n• Holder: a People's Organization (PO) — not an individual, not a corporation.\n• Term: 25 years, renewable for another 25.\n• Grants the right to occupy, develop, utilize, and manage a defined forestland area.\n• Requires a Community Resource Management Framework (CRMF) and annual work plans approved by the DENR.\n\nDistinguish the other instruments:\n• TLA — granted to corporations for logging natural forest. Largely phased out.\n• IFMA — 25-year production-sharing agreement with a corporation or individual, typically for plantation development.\n• CADT — issued by the NCIP (not the DENR) under IPRA (RA 8371), recognizing indigenous peoples' ownership of ancestral domains.\n\nThe discriminator is WHO holds it: PO → CBFMA, corporation → IFMA/TLA, ICC/IP → CADT.",
    tips: "Match holder to instrument. 'Organized community' or 'People's Organization' means CBFMA; 'indigenous peoples' switches both the instrument and the agency to CADT and NCIP.",
  },
  {
    id: "q10",
    seedId: "fbm-002",
    subject: "Forest Biometrics & Mensuration",
    difficulty: "Medium",
    question: "Using a wedge prism with a basal area factor (BAF) of 4 m²/ha, a forester counts 9 'in' trees at a sample point. What is the estimated basal area per hectare?",
    options: [
      { id: "a", text: "2.25 m²/ha" },
      { id: "b", text: "13 m²/ha" },
      { id: "c", text: "9 m²/ha" },
      { id: "d", text: "36 m²/ha" },
    ],
    correctAnswerId: "d",
    explanation: "In point sampling, basal area per hectare = tree count × BAF = 9 × 4 = 36 m²/ha.",
    detailedExplanation: "POINT SAMPLING (variable-radius, prism, or Bitterlich sampling) is the fastest field method for estimating basal area.\n\nProcedure:\n1. Stand at the sample point.\n2. Sweep a full 360° with the prism.\n3. Count every tree whose image is not fully offset — the 'in' trees.\n4. Multiply: BA/ha = count × BAF.\n\nHere: 9 × 4 = 36 m²/ha.\n\nWhy it works: the prism selects trees with probability proportional to basal area. A large tree is 'in' from much farther away than a small one, so each counted tree represents exactly BAF square meters per hectare regardless of size. No diameter measurement and no plot boundary are needed.\n\nBorderline trees are the main source of field error — measure the limiting distance, or count every other borderline tree.",
    tips: "The method reduces to count × BAF. Given a BAF and a tree count, it is a one-step multiplication — do not overthink it.",
  },
  {
    id: "q11",
    seedId: "fes-002",
    subject: "Forest Engineering & Surveying",
    difficulty: "Hard",
    question: "A forest road climbs 45 meters in elevation over a slope distance of 500 meters. What is the approximate gradient of the road?",
    options: [
      { id: "a", text: "4.5%" },
      { id: "b", text: "9%" },
      { id: "c", text: "11%" },
      { id: "d", text: "0.9%" },
    ],
    correctAnswerId: "b",
    explanation: "Gradient = (rise ÷ run) × 100 = (45 ÷ 500) × 100 = 9%. At gentle grades, slope distance closely approximates horizontal distance.",
    detailedExplanation: "Step 1: Apply the gradient formula.\n• G = (vertical rise ÷ horizontal distance) × 100\n• G = (45 ÷ 500) × 100 = 9%\n\nStep 2: Check whether slope distance matters.\n• True horizontal distance = √(500² − 45²) = √247,975 = 497.98 m\n• Recomputed: (45 ÷ 497.98) × 100 = 9.04%\n\nThe difference is negligible, which is why field foresters treat slope distance as horizontal for grades under about 10%.\n\nPRACTICAL CONTEXT: forest road standards cap sustained grades at 8–10%, with short pitches to 12–15%. At 9% a loaded log truck is near the limit for traction and brake heating.\n\nDistractors: 4.5% divides by 1,000; 11% inverts the ratio; 0.9% is a decimal-place error.",
    tips: "Gradient is rise over run as a percent. Watch the decimal: 45/500 = 0.09, and 0.09 × 100 = 9%, not 0.9%.",
  },
  {
    id: "q12",
    seedId: "frm-002",
    subject: "Forest Resources Management",
    difficulty: "Easy",
    question: "Which Philippine agency has primary jurisdiction over the management, protection, and sustainable development of the country's forestlands?",
    options: [
      { id: "a", text: "Department of Agriculture (DA)" },
      { id: "b", text: "Department of Agrarian Reform (DAR)" },
      { id: "c", text: "National Commission on Indigenous Peoples (NCIP)" },
      { id: "d", text: "Department of Environment and Natural Resources (DENR)" },
    ],
    correctAnswerId: "d",
    explanation: "The DENR, through its Forest Management Bureau (FMB), is the primary agency responsible for the conservation, management, development, and proper use of the country's forest resources.",
    detailedExplanation: "The DENR was created under Executive Order No. 192 (1987).\n\nRelevant DENR bureaus:\n• FOREST MANAGEMENT BUREAU (FMB) — policy and technical guidance on forestland management.\n• BIODIVERSITY MANAGEMENT BUREAU (BMB) — protected areas and wildlife (formerly PAWB).\n• ERDB — Ecosystems Research and Development Bureau, the research arm.\n• LAND MANAGEMENT BUREAU (LMB) — alienable and disposable lands.\n\nJurisdiction of the others:\n• DA — agricultural lands and crops, NOT forestlands.\n• DAR — agrarian reform on private agricultural land under CARP.\n• NCIP — ancestral domains under IPRA (RA 8371).\n\nField implementation runs DENR Regional Office → PENRO (provincial) → CENRO (community).",
    tips: "Learn the chain of command: DENR → Regional Office → PENRO → CENRO. Exams frequently ask which office issues a permit — usually the CENRO at field level.",
  },
];

export const mockUserProgress: UserProgress = {
  questionsAnswered: 168,
  correctAnswers: 124,
  accuracy: 74,
  weakestSubject: "Forest Biometrics & Mensuration",
  daysUntilExam: 52,
  lastSessionQuestionId: "q3",
};
