-- ============================================================================
-- ForestGuro — Migration 0005: hand-authored core question bank
--
-- 180 questions: 6 board subjects x 3 difficulties x 10.
--
-- These are the verified backbone of the bank. Every correct answer here is
-- checkable against Philippine forestry law, a standard mensuration formula, or
-- settled wood science — not inferred. The generated questions produced by
-- scripts/generate-questions.ts are measured against this set.
--
-- Within each subject/difficulty block of 10, the first 4 go to the practice
-- pool and the remaining 6 to mock, mirroring the 2000/3000 target split.
--
-- explanation is deliberately left NULL. The first user to answer a question
-- triggers one OpenAI call, and the result is written back to the row.
--
-- Run AFTER 0004_question_pools.sql. Safe to re-run: re-running updates the
-- question text and options but never overwrites an explanation already
-- generated for a row.
-- ============================================================================

insert into public.questions
  (id, subject, difficulty, pool, question, options, correct_answer_id)
values

-- ============================================================================
-- SILVICULTURE & FOREST ECOLOGY
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('sil-101', 'Silviculture & Forest Ecology', 'Easy', 'practice',
 'Which silvicultural system regenerates a stand from stump sprouts or root suckers rather than from seed?',
 '[{"id": "a", "text": "Coppice system"}, {"id": "b", "text": "Shelterwood system"}, {"id": "c", "text": "Selection system"}, {"id": "d", "text": "Seed-tree system"}]'::jsonb, 'a'),
('sil-102', 'Silviculture & Forest Ecology', 'Easy', 'practice',
 'What is the national tree of the Philippines?',
 '[{"id": "a", "text": "Molave (Vitex parviflora)"}, {"id": "b", "text": "Narra (Pterocarpus indicus)"}, {"id": "c", "text": "Yakal (Shorea astylosa)"}, {"id": "d", "text": "Apitong (Dipterocarpus grandiflorus)"}]'::jsonb, 'b'),
('sil-103', 'Silviculture & Forest Ecology', 'Easy', 'practice',
 'A species that establishes on bare, disturbed ground and is later replaced by other species is best described as a:',
 '[{"id": "a", "text": "Climax species"}, {"id": "b", "text": "Shade-tolerant species"}, {"id": "c", "text": "Pioneer species"}, {"id": "d", "text": "Endemic species"}]'::jsonb, 'c'),
('sil-104', 'Silviculture & Forest Ecology', 'Easy', 'practice',
 'The symbiotic association between fungi and tree roots that improves nutrient uptake is called:',
 '[{"id": "a", "text": "Rhizobium nodulation"}, {"id": "b", "text": "Parasitism"}, {"id": "c", "text": "Mycorrhiza"}, {"id": "d", "text": "Epiphytism"}]'::jsonb, 'c'),
('sil-105', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'Which pine species dominates the montane forests of the Cordillera region?',
 '[{"id": "a", "text": "Pinus merkusii"}, {"id": "b", "text": "Pinus kesiya"}, {"id": "c", "text": "Pinus caribaea"}, {"id": "d", "text": "Agathis philippinensis"}]'::jsonb, 'b'),
('sil-106', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'The primary silvicultural purpose of thinning an even-aged stand is to:',
 '[{"id": "a", "text": "Harvest the final crop"}, {"id": "b", "text": "Establish natural regeneration"}, {"id": "c", "text": "Convert the stand to uneven-aged structure"}, {"id": "d", "text": "Redistribute growth onto the remaining trees"}]'::jsonb, 'd'),
('sil-107', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'A shade-tolerant species is one that can:',
 '[{"id": "a", "text": "Grow only in full sunlight"}, {"id": "b", "text": "Tolerate prolonged flooding"}, {"id": "c", "text": "Survive and grow under a closed canopy"}, {"id": "d", "text": "Withstand repeated ground fires"}]'::jsonb, 'c'),
('sil-108', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'Which family dominates the Philippine lowland evergreen rainforest and supplies most commercial lauan timber?',
 '[{"id": "a", "text": "Dipterocarpaceae"}, {"id": "b", "text": "Fabaceae"}, {"id": "c", "text": "Myrtaceae"}, {"id": "d", "text": "Moraceae"}]'::jsonb, 'a'),
('sil-109', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'The relatively stable, self-perpetuating community that ends a successional sequence is called the:',
 '[{"id": "a", "text": "Climax community"}, {"id": "b", "text": "Seral stage"}, {"id": "c", "text": "Pioneer stage"}, {"id": "d", "text": "Disclimax"}]'::jsonb, 'a'),
('sil-110', 'Silviculture & Forest Ecology', 'Easy', 'mock',
 'Trees planted mainly to shelter a more valuable species during establishment are called:',
 '[{"id": "a", "text": "Nurse trees"}, {"id": "b", "text": "Seed trees"}, {"id": "c", "text": "Standards"}, {"id": "d", "text": "Wolf trees"}]'::jsonb, 'a'),

-- Medium ----------------------------------------------------------------------
('sil-111', 'Silviculture & Forest Ecology', 'Medium', 'practice',
 'In the shelterwood system, which cutting removes the last of the overstory once regeneration is established?',
 '[{"id": "a", "text": "Preparatory cutting"}, {"id": "b", "text": "Removal cutting"}, {"id": "c", "text": "Seed cutting"}, {"id": "d", "text": "Improvement cutting"}]'::jsonb, 'b'),
('sil-112', 'Silviculture & Forest Ecology', 'Medium', 'practice',
 'Assisted Natural Regeneration (ANR) works chiefly by:',
 '[{"id": "a", "text": "Releasing existing wildlings from grass competition"}, {"id": "b", "text": "Planting nursery-raised seedlings at close spacing"}, {"id": "c", "text": "Direct seeding of exotic species"}, {"id": "d", "text": "Applying fertiliser to degraded soil"}]'::jsonb, 'a'),
('sil-113', 'Silviculture & Forest Ecology', 'Medium', 'practice',
 'Site index expresses site productivity as the:',
 '[{"id": "a", "text": "Average diameter of dominant trees at a reference age"}, {"id": "b", "text": "Basal area per hectare at rotation age"}, {"id": "c", "text": "Height of dominant trees at a reference age"}, {"id": "d", "text": "Number of stems per hectare at establishment"}]'::jsonb, 'c'),
('sil-114', 'Silviculture & Forest Ecology', 'Medium', 'practice',
 'The release of chemical compounds by one plant that suppresses the germination or growth of another is called:',
 '[{"id": "a", "text": "Symbiosis"}, {"id": "b", "text": "Allelopathy"}, {"id": "c", "text": "Commensalism"}, {"id": "d", "text": "Etiolation"}]'::jsonb, 'b'),
('sil-115', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'Girdling an undesirable tree in a timber stand improvement operation kills it by:',
 '[{"id": "a", "text": "Severing the xylem and stopping water uptake"}, {"id": "b", "text": "Exposing the cambium to direct sunlight"}, {"id": "c", "text": "Introducing decay fungi into the heartwood"}, {"id": "d", "text": "Interrupting phloem transport of photosynthates to the roots"}]'::jsonb, 'd'),
('sil-116', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'Succession beginning on a substrate that has never carried vegetation, such as a fresh lava flow, is termed:',
 '[{"id": "a", "text": "Secondary succession"}, {"id": "b", "text": "Primary succession"}, {"id": "c", "text": "Cyclic succession"}, {"id": "d", "text": "Retrogressive succession"}]'::jsonb, 'b'),
('sil-117', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'Enrichment planting is most appropriately applied in:',
 '[{"id": "a", "text": "A bare, fully exposed grassland site"}, {"id": "b", "text": "An intact primary dipterocarp forest"}, {"id": "c", "text": "A mangrove fringe subject to daily tidal inundation"}, {"id": "d", "text": "A logged-over residual forest with gaps in the canopy"}]'::jsonb, 'd'),
('sil-118', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'Which mangrove genus is most characteristic of the seaward zone and bears distinctive stilt roots?',
 '[{"id": "a", "text": "Rhizophora"}, {"id": "b", "text": "Avicennia"}, {"id": "c", "text": "Nypa"}, {"id": "d", "text": "Xylocarpus"}]'::jsonb, 'a'),
('sil-119', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'The selection system is best suited to species that are:',
 '[{"id": "a", "text": "Light-demanding and fast-growing"}, {"id": "b", "text": "Fire-dependent for seed release"}, {"id": "c", "text": "Shade-tolerant and capable of regenerating under canopy"}, {"id": "d", "text": "Nitrogen-fixing pioneers"}]'::jsonb, 'c'),
('sil-120', 'Silviculture & Forest Ecology', 'Medium', 'mock',
 'Dipterocarps are noted for a reproductive pattern in which flowering and fruiting occur:',
 '[{"id": "a", "text": "At irregular multi-year intervals in synchronised mast events"}, {"id": "b", "text": "Every year with uniform intensity"}, {"id": "c", "text": "Continuously throughout the year"}, {"id": "d", "text": "Only after the passage of fire"}]'::jsonb, 'a'),

-- Hard ------------------------------------------------------------------------
('sil-121', 'Silviculture & Forest Ecology', 'Hard', 'practice',
 'A balanced uneven-aged stand plotted as number of trees against diameter class typically produces which curve?',
 '[{"id": "a", "text": "A normal bell-shaped curve"}, {"id": "b", "text": "A bimodal curve"}, {"id": "c", "text": "A reverse J-shaped curve"}, {"id": "d", "text": "A uniform flat distribution"}]'::jsonb, 'c'),
('sil-122', 'Silviculture & Forest Ecology', 'Hard', 'practice',
 'In seed orchard management, the main purpose of establishing clones from many unrelated plus trees is to:',
 '[{"id": "a", "text": "Maximise seed yield per hectare"}, {"id": "b", "text": "Shorten the time to first flowering"}, {"id": "c", "text": "Maintain genetic diversity and limit inbreeding depression"}, {"id": "d", "text": "Reduce the cost of seed collection"}]'::jsonb, 'c'),
('sil-123', 'Silviculture & Forest Ecology', 'Hard', 'practice',
 'A provenance trial is designed primarily to test:',
 '[{"id": "a", "text": "Performance of seed sources from different geographic origins on a common site"}, {"id": "b", "text": "Different silvicultural treatments on one seed source"}, {"id": "c", "text": "Fertiliser response across soil types"}, {"id": "d", "text": "Spacing effects on stem form"}]'::jsonb, 'a'),
('sil-124', 'Silviculture & Forest Ecology', 'Hard', 'practice',
 'Gap dynamics theory explains species coexistence in tropical rainforest chiefly through:',
 '[{"id": "a", "text": "Uniform light availability across the forest floor"}, {"id": "b", "text": "Competitive exclusion by a single dominant species"}, {"id": "c", "text": "Variation in gap size creating niches for species of differing light requirements"}, {"id": "d", "text": "Periodic stand-replacing fire"}]'::jsonb, 'c'),
('sil-125', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'Species characterised by rapid growth, early reproduction and abundant small seeds are described in life-history theory as:',
 '[{"id": "a", "text": "K-selected"}, {"id": "b", "text": "Facultative"}, {"id": "c", "text": "Obligate"}, {"id": "d", "text": "r-selected"}]'::jsonb, 'd'),
('sil-126', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'The edge effect that follows forest fragmentation typically produces, near the boundary, conditions that are:',
 '[{"id": "a", "text": "Cooler, more humid and less windy"}, {"id": "b", "text": "Unchanged from interior forest"}, {"id": "c", "text": "Higher in soil organic matter"}, {"id": "d", "text": "Warmer, drier and more exposed to wind"}]'::jsonb, 'd'),
('sil-127', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'A soil seed bank contributes most strongly to regeneration after:',
 '[{"id": "a", "text": "Selective removal of a single mature tree"}, {"id": "b", "text": "Prolonged canopy closure"}, {"id": "c", "text": "A disturbance that opens the canopy and exposes mineral soil"}, {"id": "d", "text": "Underplanting with shade-tolerant seedlings"}]'::jsonb, 'c'),
('sil-128', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'In the Philippine Selective Logging System, the residual stand to be retained after harvest is defined primarily by:',
 '[{"id": "a", "text": "The total volume removed per hectare"}, {"id": "b", "text": "The number of species present"}, {"id": "c", "text": "The age of the dominant trees"}, {"id": "d", "text": "Adequate healthy residuals in the smaller diameter classes to form the next crop"}]'::jsonb, 'd'),
('sil-129', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'Ecological succession that moves toward a simpler, less productive community following sustained degradation is called:',
 '[{"id": "a", "text": "Progressive succession"}, {"id": "b", "text": "Allogenic succession"}, {"id": "c", "text": "Retrogressive succession"}, {"id": "d", "text": "Autogenic succession"}]'::jsonb, 'c'),
('sil-130', 'Silviculture & Forest Ecology', 'Hard', 'mock',
 'Crown classes in an even-aged stand rank trees by light exposure. Which class receives light from above but not from the sides?',
 '[{"id": "a", "text": "Codominant"}, {"id": "b", "text": "Dominant"}, {"id": "c", "text": "Intermediate"}, {"id": "d", "text": "Suppressed"}]'::jsonb, 'a'),

-- ============================================================================
-- FOREST RESOURCES MANAGEMENT
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('frm-101', 'Forest Resources Management', 'Easy', 'practice',
 'The maximum volume that may be harvested annually from a forest without depleting the growing stock is the:',
 '[{"id": "a", "text": "Mean annual increment"}, {"id": "b", "text": "Standing volume"}, {"id": "c", "text": "Annual allowable cut"}, {"id": "d", "text": "Rotation age"}]'::jsonb, 'c'),
('frm-102', 'Forest Resources Management', 'Easy', 'practice',
 'The planned number of years between establishment and final harvest of an even-aged crop is the:',
 '[{"id": "a", "text": "Cutting cycle"}, {"id": "b", "text": "Felling series"}, {"id": "c", "text": "Rotation"}, {"id": "d", "text": "Regeneration period"}]'::jsonb, 'c'),
('frm-103', 'Forest Resources Management', 'Easy', 'practice',
 'Which Philippine agency has primary jurisdiction over forest lands and their management?',
 '[{"id": "a", "text": "Department of Agriculture"}, {"id": "b", "text": "Department of Agrarian Reform"}, {"id": "c", "text": "Department of Science and Technology"}, {"id": "d", "text": "Department of Environment and Natural Resources"}]'::jsonb, 'd'),
('frm-104', 'Forest Resources Management', 'Easy', 'practice',
 'A forest inventory is conducted primarily to determine:',
 '[{"id": "a", "text": "The legal boundary of a tenure area"}, {"id": "b", "text": "The market price of timber"}, {"id": "c", "text": "The quantity, quality and distribution of the forest resource"}, {"id": "d", "text": "The number of workers required for harvest"}]'::jsonb, 'c'),
('frm-105', 'Forest Resources Management', 'Easy', 'mock',
 'Sustained yield management aims to achieve:',
 '[{"id": "a", "text": "A continuous and approximately equal periodic yield in perpetuity"}, {"id": "b", "text": "Maximum harvest in the shortest possible time"}, {"id": "c", "text": "Complete protection with no harvesting"}, {"id": "d", "text": "Conversion of natural forest to plantation"}]'::jsonb, 'a'),
('frm-106', 'Forest Resources Management', 'Easy', 'mock',
 'The document that sets out prescribed management activities for a forest area over a defined period is the:',
 '[{"id": "a", "text": "Environmental compliance certificate"}, {"id": "b", "text": "Forest management plan or working plan"}, {"id": "c", "text": "Timber licence agreement"}, {"id": "d", "text": "Certificate of ancestral domain title"}]'::jsonb, 'b'),
('frm-107', 'Forest Resources Management', 'Easy', 'mock',
 'In a normal forest under area control, the age classes are:',
 '[{"id": "a", "text": "Concentrated in the oldest class"}, {"id": "b", "text": "Randomly distributed"}, {"id": "c", "text": "Represented in equal areas from youngest to rotation age"}, {"id": "d", "text": "Absent below half the rotation age"}]'::jsonb, 'c'),
('frm-108', 'Forest Resources Management', 'Easy', 'mock',
 'Non-timber forest products include all of the following EXCEPT:',
 '[{"id": "a", "text": "Sawn lumber"}, {"id": "b", "text": "Rattan"}, {"id": "c", "text": "Almaciga resin"}, {"id": "d", "text": "Honey"}]'::jsonb, 'a'),
('frm-109', 'Forest Resources Management', 'Easy', 'mock',
 'The total volume of standing trees in a forest at a given time is the:',
 '[{"id": "a", "text": "Annual allowable cut"}, {"id": "b", "text": "Increment"}, {"id": "c", "text": "Growing stock"}, {"id": "d", "text": "Yield"}]'::jsonb, 'c'),
('frm-110', 'Forest Resources Management', 'Easy', 'mock',
 'A cutting cycle in an uneven-aged forest refers to the:',
 '[{"id": "a", "text": "Age at which trees are felled"}, {"id": "b", "text": "Interval between successive harvests in the same stand"}, {"id": "c", "text": "Time needed for regeneration to establish"}, {"id": "d", "text": "Period covered by the management plan"}]'::jsonb, 'b'),

-- Medium ----------------------------------------------------------------------
('frm-111', 'Forest Resources Management', 'Medium', 'practice',
 'A 600-hectare plantation is managed on a 30-year rotation under strict area control. What area should be harvested each year?',
 '[{"id": "a", "text": "15 hectares"}, {"id": "b", "text": "20 hectares"}, {"id": "c", "text": "25 hectares"}, {"id": "d", "text": "30 hectares"}]'::jsonb, 'b'),
('frm-112', 'Forest Resources Management', 'Medium', 'practice',
 'A stand holds 300 cubic metres per hectare at age 25. What is its mean annual increment?',
 '[{"id": "a", "text": "10 m3/ha/yr"}, {"id": "b", "text": "12 m3/ha/yr"}, {"id": "c", "text": "15 m3/ha/yr"}, {"id": "d", "text": "25 m3/ha/yr"}]'::jsonb, 'b'),
('frm-113', 'Forest Resources Management', 'Medium', 'practice',
 'The biological rotation for maximum volume production occurs when:',
 '[{"id": "a", "text": "Current annual increment reaches its maximum"}, {"id": "b", "text": "Mean annual increment first becomes positive"}, {"id": "c", "text": "Current annual increment equals mean annual increment"}, {"id": "d", "text": "Current annual increment falls to zero"}]'::jsonb, 'c'),
('frm-114', 'Forest Resources Management', 'Medium', 'practice',
 'Volume control differs from area control in that volume control regulates the harvest by:',
 '[{"id": "a", "text": "Dividing the forest into equal annual coupes"}, {"id": "b", "text": "Fixing the number of trees per hectare"}, {"id": "c", "text": "Setting a minimum diameter limit only"}, {"id": "d", "text": "Limiting the quantity of wood removed rather than the area cut"}]'::jsonb, 'd'),
('frm-115', 'Forest Resources Management', 'Medium', 'mock',
 'Under the Von Mantel formula, annual allowable cut is estimated as:',
 '[{"id": "a", "text": "Growing stock divided by rotation"}, {"id": "b", "text": "Growing stock multiplied by the rotation"}, {"id": "c", "text": "Twice the growing stock divided by the rotation"}, {"id": "d", "text": "Increment divided by growing stock"}]'::jsonb, 'c'),
('frm-116', 'Forest Resources Management', 'Medium', 'mock',
 'Current annual increment exceeds mean annual increment during which phase of stand development?',
 '[{"id": "a", "text": "After culmination of mean annual increment"}, {"id": "b", "text": "Only at rotation age"}, {"id": "c", "text": "Throughout the entire rotation"}, {"id": "d", "text": "Before culmination of mean annual increment"}]'::jsonb, 'd'),
('frm-117', 'Forest Resources Management', 'Medium', 'mock',
 'A forest with 8,000 cubic metres of growing stock and a 40-year rotation gives what annual allowable cut under Von Mantel?',
 '[{"id": "a", "text": "100 m3"}, {"id": "b", "text": "200 m3"}, {"id": "c", "text": "400 m3"}, {"id": "d", "text": "800 m3"}]'::jsonb, 'c'),
('frm-118', 'Forest Resources Management', 'Medium', 'mock',
 'Multiple-use forest management means managing the same forest area for:',
 '[{"id": "a", "text": "Timber production only, at maximum intensity"}, {"id": "b", "text": "Strict protection with no extraction"}, {"id": "c", "text": "Several compatible benefits such as timber, water, wildlife and recreation"}, {"id": "d", "text": "Agricultural conversion"}]'::jsonb, 'c'),
('frm-119', 'Forest Resources Management', 'Medium', 'mock',
 'A compartment in forest management is best defined as:',
 '[{"id": "a", "text": "A permanent territorial unit of the forest used for record keeping and planning"}, {"id": "b", "text": "A temporary logging camp"}, {"id": "c", "text": "A single age class within a stand"}, {"id": "d", "text": "The area harvested in one year"}]'::jsonb, 'a'),
('frm-120', 'Forest Resources Management', 'Medium', 'mock',
 'If a 1,000-hectare forest is managed on a 50-year rotation, the normal area of each age class is:',
 '[{"id": "a", "text": "10 hectares"}, {"id": "b", "text": "20 hectares"}, {"id": "c", "text": "50 hectares"}, {"id": "d", "text": "100 hectares"}]'::jsonb, 'b'),

-- Hard ------------------------------------------------------------------------
('frm-121', 'Forest Resources Management', 'Hard', 'practice',
 'The Faustmann formula determines the value of:',
 '[{"id": "a", "text": "Standing timber at current market prices"}, {"id": "b", "text": "Annual harvesting costs"}, {"id": "c", "text": "The carbon stock of a stand"}, {"id": "d", "text": "Bare forest land under an infinite series of identical rotations"}]'::jsonb, 'd'),
('frm-122', 'Forest Resources Management', 'Hard', 'practice',
 'The financial rotation is generally shorter than the biological rotation because:',
 '[{"id": "a", "text": "Trees stop growing earlier than expected"}, {"id": "b", "text": "Timber prices always fall over time"}, {"id": "c", "text": "Harvesting costs decline with stand age"}, {"id": "d", "text": "Discounting reduces the present value of distant future revenues"}]'::jsonb, 'd'),
('frm-123', 'Forest Resources Management', 'Hard', 'practice',
 'Under the Hanzlik formula, annual allowable cut is computed as the volume of mature timber divided by the rotation, plus:',
 '[{"id": "a", "text": "The growing stock"}, {"id": "b", "text": "The area of the forest"}, {"id": "c", "text": "The annual increment of immature stands"}, {"id": "d", "text": "The salvage volume"}]'::jsonb, 'c'),
('frm-124', 'Forest Resources Management', 'Hard', 'practice',
 'A project has a positive net present value at a 10 percent discount rate. This means the project:',
 '[{"id": "a", "text": "Has an internal rate of return below 10 percent"}, {"id": "b", "text": "Will break even exactly at 10 percent"}, {"id": "c", "text": "Cannot be evaluated without the payback period"}, {"id": "d", "text": "Has an internal rate of return above 10 percent"}]'::jsonb, 'd'),
('frm-125', 'Forest Resources Management', 'Hard', 'mock',
 'The Austrian formula adjusts the annual allowable cut by distributing the difference between actual and normal growing stock over:',
 '[{"id": "a", "text": "An adjustment period of several years"}, {"id": "b", "text": "One year"}, {"id": "c", "text": "The full rotation only"}, {"id": "d", "text": "The cutting cycle of the oldest compartment"}]'::jsonb, 'a'),
('frm-126', 'Forest Resources Management', 'Hard', 'mock',
 'In forest valuation, the expectation value of a young stand is derived from:',
 '[{"id": "a", "text": "Its current sale value as standing timber"}, {"id": "b", "text": "The discounted value of expected future revenues less future costs"}, {"id": "c", "text": "The accumulated cost of establishment to date"}, {"id": "d", "text": "The replacement cost of the seedlings"}]'::jsonb, 'b'),
('frm-127', 'Forest Resources Management', 'Hard', 'mock',
 'A stand table projection estimates future stand structure principally by applying:',
 '[{"id": "a", "text": "A single average growth rate to total volume"}, {"id": "b", "text": "The rotation age to the current basal area"}, {"id": "c", "text": "Diameter-class transition and mortality rates over a growth period"}, {"id": "d", "text": "The site index curve to stand height"}]'::jsonb, 'c'),
('frm-128', 'Forest Resources Management', 'Hard', 'mock',
 'A 400-hectare forest is under a 20-year cutting cycle with selective harvesting. How much area is entered annually?',
 '[{"id": "a", "text": "10 hectares"}, {"id": "b", "text": "20 hectares"}, {"id": "c", "text": "40 hectares"}, {"id": "d", "text": "80 hectares"}]'::jsonb, 'b'),
('frm-129', 'Forest Resources Management', 'Hard', 'mock',
 'The normal growing stock of a fully regulated forest is most nearly equal to:',
 '[{"id": "a", "text": "The annual allowable cut times the rotation"}, {"id": "b", "text": "Approximately half the yield at rotation age times the rotation"}, {"id": "c", "text": "The mean annual increment"}, {"id": "d", "text": "The area divided by the rotation"}]'::jsonb, 'b'),
('frm-130', 'Forest Resources Management', 'Hard', 'mock',
 'Reduced-impact logging lowers residual stand damage mainly through:',
 '[{"id": "a", "text": "Pre-harvest inventory, planned skid trails and directional felling"}, {"id": "b", "text": "Increasing the diameter cutting limit"}, {"id": "c", "text": "Using larger machinery to shorten operations"}, {"id": "d", "text": "Harvesting only during the wet season"}]'::jsonb, 'a'),

-- ============================================================================
-- FOREST ENGINEERING & SURVEYING
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('fes-101', 'Forest Engineering & Surveying', 'Easy', 'practice',
 'A bearing of N 30 deg E corresponds to what azimuth measured clockwise from north?',
 '[{"id": "a", "text": "30 degrees"}, {"id": "b", "text": "60 degrees"}, {"id": "c", "text": "150 degrees"}, {"id": "d", "text": "330 degrees"}]'::jsonb, 'a'),
('fes-102', 'Forest Engineering & Surveying', 'Easy', 'practice',
 'A line on a map joining points of equal elevation is a:',
 '[{"id": "a", "text": "Traverse line"}, {"id": "b", "text": "Contour line"}, {"id": "c", "text": "Meridian"}, {"id": "d", "text": "Baseline"}]'::jsonb, 'b'),
('fes-103', 'Forest Engineering & Surveying', 'Easy', 'practice',
 'Which instrument is used to measure vertical angles or slope in the field?',
 '[{"id": "a", "text": "Planimeter"}, {"id": "b", "text": "Alidade"}, {"id": "c", "text": "Clinometer"}, {"id": "d", "text": "Stadia rod"}]'::jsonb, 'c'),
('fes-104', 'Forest Engineering & Surveying', 'Easy', 'practice',
 'GIS stands for:',
 '[{"id": "a", "text": "Global Inventory Standard"}, {"id": "b", "text": "Geographic Information System"}, {"id": "c", "text": "Ground Instrument Survey"}, {"id": "d", "text": "General Inventory Software"}]'::jsonb, 'b'),
('fes-105', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'A closed traverse is one in which the survey:',
 '[{"id": "a", "text": "Follows a single straight line"}, {"id": "b", "text": "Begins and ends at the same point or at known points"}, {"id": "c", "text": "Uses only compass bearings"}, {"id": "d", "text": "Is run entirely downhill"}]'::jsonb, 'b'),
('fes-106', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'The sum of the interior angles of a closed five-sided traverse is:',
 '[{"id": "a", "text": "360 degrees"}, {"id": "b", "text": "450 degrees"}, {"id": "c", "text": "540 degrees"}, {"id": "d", "text": "720 degrees"}]'::jsonb, 'c'),
('fes-107', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'Differential levelling is used mainly to determine:',
 '[{"id": "a", "text": "Difference in elevation between two points"}, {"id": "b", "text": "Horizontal distance between two points"}, {"id": "c", "text": "Magnetic declination"}, {"id": "d", "text": "Area of a parcel"}]'::jsonb, 'a'),
('fes-108', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'One hectare is equal to:',
 '[{"id": "a", "text": "1,000 square metres"}, {"id": "b", "text": "10,000 square metres"}, {"id": "c", "text": "100,000 square metres"}, {"id": "d", "text": "1,000,000 square metres"}]'::jsonb, 'b'),
('fes-109', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'In cable yarding, logs are moved to the landing by:',
 '[{"id": "a", "text": "Suspension from an overhead cable system"}, {"id": "b", "text": "Dragging behind a ground skidder"}, {"id": "c", "text": "Floating down a watercourse"}, {"id": "d", "text": "Carrying on a forwarder bunk"}]'::jsonb, 'a'),
('fes-110', 'Forest Engineering & Surveying', 'Easy', 'mock',
 'The angle between true north and magnetic north at a given place is called:',
 '[{"id": "a", "text": "Azimuth"}, {"id": "b", "text": "Magnetic declination"}, {"id": "c", "text": "Bearing"}, {"id": "d", "text": "Deflection angle"}]'::jsonb, 'b'),

-- Medium ----------------------------------------------------------------------
('fes-111', 'Forest Engineering & Surveying', 'Medium', 'practice',
 'A forest road rises 6 metres over a horizontal distance of 120 metres. What is its gradient?',
 '[{"id": "a", "text": "2 percent"}, {"id": "b", "text": "5 percent"}, {"id": "c", "text": "6 percent"}, {"id": "d", "text": "12 percent"}]'::jsonb, 'b'),
('fes-112', 'Forest Engineering & Surveying', 'Medium', 'practice',
 'The latitude of a traverse course is its component along which direction?',
 '[{"id": "a", "text": "East-west"}, {"id": "b", "text": "Vertical"}, {"id": "c", "text": "Along the slope"}, {"id": "d", "text": "North-south"}]'::jsonb, 'd'),
('fes-113', 'Forest Engineering & Surveying', 'Medium', 'practice',
 'A slope distance of 50 metres is measured on ground inclined at 30 degrees. What is the horizontal distance?',
 '[{"id": "a", "text": "25.0 metres"}, {"id": "b", "text": "43.3 metres"}, {"id": "c", "text": "50.0 metres"}, {"id": "d", "text": "57.7 metres"}]'::jsonb, 'b'),
('fes-114', 'Forest Engineering & Surveying', 'Medium', 'practice',
 'In a closed traverse, the algebraic sum of all latitudes and the algebraic sum of all departures should each equal:',
 '[{"id": "a", "text": "The perimeter"}, {"id": "b", "text": "The area"}, {"id": "c", "text": "The longest course length"}, {"id": "d", "text": "Zero"}]'::jsonb, 'd'),
('fes-115', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'The back azimuth of a line whose forward azimuth is 75 degrees is:',
 '[{"id": "a", "text": "105 degrees"}, {"id": "b", "text": "255 degrees"}, {"id": "c", "text": "285 degrees"}, {"id": "d", "text": "345 degrees"}]'::jsonb, 'b'),
('fes-116', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'A rectangular plantation block measures 200 metres by 250 metres. What is its area?',
 '[{"id": "a", "text": "2 hectares"}, {"id": "b", "text": "5 hectares"}, {"id": "c", "text": "10 hectares"}, {"id": "d", "text": "50 hectares"}]'::jsonb, 'b'),
('fes-117', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'The primary engineering reason for limiting forest road gradient is to:',
 '[{"id": "a", "text": "Reduce construction cost only"}, {"id": "b", "text": "Shorten total road length"}, {"id": "c", "text": "Keep hauling within safe traction limits and control surface erosion"}, {"id": "d", "text": "Improve sight distance at curves"}]'::jsonb, 'c'),
('fes-118', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'A culvert on a forest road is installed principally to:',
 '[{"id": "a", "text": "Support heavy axle loads"}, {"id": "b", "text": "Mark the road centreline"}, {"id": "c", "text": "Carry stream or drainage flow beneath the roadway"}, {"id": "d", "text": "Reduce the road gradient"}]'::jsonb, 'c'),
('fes-119', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'Using a clinometer at 20 metres horizontal distance, the readings to the top and base of a tree are +55 percent and -5 percent. What is the tree height?',
 '[{"id": "a", "text": "10 metres"}, {"id": "b", "text": "11 metres"}, {"id": "c", "text": "12 metres"}, {"id": "d", "text": "20 metres"}]'::jsonb, 'c'),
('fes-120', 'Forest Engineering & Surveying', 'Medium', 'mock',
 'The double meridian distance method is used to compute:',
 '[{"id": "a", "text": "Elevation differences"}, {"id": "b", "text": "Magnetic declination"}, {"id": "c", "text": "Curve radius"}, {"id": "d", "text": "The area enclosed by a closed traverse"}]'::jsonb, 'd'),

-- Hard ------------------------------------------------------------------------
('fes-121', 'Forest Engineering & Surveying', 'Hard', 'practice',
 'A traverse has a closure error in latitude of 0.3 metres and in departure of 0.4 metres over a perimeter of 1,000 metres. What is the relative error of closure?',
 '[{"id": "a", "text": "1 in 1,000"}, {"id": "b", "text": "1 in 2,000"}, {"id": "c", "text": "1 in 2,500"}, {"id": "d", "text": "1 in 5,000"}]'::jsonb, 'b'),
('fes-122', 'Forest Engineering & Surveying', 'Hard', 'practice',
 'The compass rule distributes traverse closure error in proportion to:',
 '[{"id": "a", "text": "The length of each course"}, {"id": "b", "text": "The latitude of each course only"}, {"id": "c", "text": "The interior angle at each station"}, {"id": "d", "text": "The elevation change of each course"}]'::jsonb, 'a'),
('fes-123', 'Forest Engineering & Surveying', 'Hard', 'practice',
 'Switchbacks are introduced in forest road layout primarily to:',
 '[{"id": "a", "text": "Gain elevation on steep terrain while holding gradient within limits"}, {"id": "b", "text": "Shorten the total distance travelled"}, {"id": "c", "text": "Provide passing bays for trucks"}, {"id": "d", "text": "Reduce the number of culverts required"}]'::jsonb, 'a'),
('fes-124', 'Forest Engineering & Surveying', 'Hard', 'practice',
 'In earthwork computation, the average end area method estimates volume between two cross-sections as:',
 '[{"id": "a", "text": "The product of the two end areas"}, {"id": "b", "text": "The difference of the end areas divided by two"}, {"id": "c", "text": "The larger end area times the distance"}, {"id": "d", "text": "The mean of the two end areas multiplied by the distance between them"}]'::jsonb, 'd'),
('fes-125', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'A ground slope of 100 percent corresponds to an angle of:',
 '[{"id": "a", "text": "30 degrees"}, {"id": "b", "text": "45 degrees"}, {"id": "c", "text": "60 degrees"}, {"id": "d", "text": "90 degrees"}]'::jsonb, 'b'),
('fes-126', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'Stadia measurement determines horizontal distance principally from:',
 '[{"id": "a", "text": "The vertical angle alone"}, {"id": "b", "text": "The magnetic bearing of the sight line"}, {"id": "c", "text": "The elapsed time of a laser pulse"}, {"id": "d", "text": "The rod intercept between stadia hairs multiplied by a stadia constant"}]'::jsonb, 'd'),
('fes-127', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'The degree of curve of a horizontal road curve is inversely related to its:',
 '[{"id": "a", "text": "Radius"}, {"id": "b", "text": "Tangent length"}, {"id": "c", "text": "External distance"}, {"id": "d", "text": "Superelevation"}]'::jsonb, 'a'),
('fes-128', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'Skyline yarding is generally preferred over ground skidding on steep slopes because it:',
 '[{"id": "a", "text": "Reduces soil disturbance and residual stand damage"}, {"id": "b", "text": "Costs less to set up"}, {"id": "c", "text": "Requires no roads at all"}, {"id": "d", "text": "Allows heavier payloads per turn"}]'::jsonb, 'a'),
('fes-129', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'A plot of radius 11.28 metres has an area closest to:',
 '[{"id": "a", "text": "200 square metres"}, {"id": "b", "text": "400 square metres"}, {"id": "c", "text": "600 square metres"}, {"id": "d", "text": "1,000 square metres"}]'::jsonb, 'b'),
('fes-130', 'Forest Engineering & Surveying', 'Hard', 'mock',
 'Remote sensing imagery is described as having high spatial resolution when it has:',
 '[{"id": "a", "text": "Many spectral bands"}, {"id": "b", "text": "A short revisit interval"}, {"id": "c", "text": "A small ground sample distance per pixel"}, {"id": "d", "text": "A wide swath width"}]'::jsonb, 'c'),

-- ============================================================================
-- WOOD SCIENCE & FOREST PRODUCTS
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('wsf-101', 'Wood Science & Forest Products', 'Easy', 'practice',
 'The inner, usually darker wood that no longer conducts sap is called:',
 '[{"id": "a", "text": "Sapwood"}, {"id": "b", "text": "Heartwood"}, {"id": "c", "text": "Cambium"}, {"id": "d", "text": "Bark"}]'::jsonb, 'b'),
('wsf-102', 'Wood Science & Forest Products', 'Easy', 'practice',
 'The fibre saturation point of wood occurs at approximately what moisture content?',
 '[{"id": "a", "text": "12 percent"}, {"id": "b", "text": "20 percent"}, {"id": "c", "text": "30 percent"}, {"id": "d", "text": "50 percent"}]'::jsonb, 'c'),
('wsf-103', 'Wood Science & Forest Products', 'Easy', 'practice',
 'Softwoods are produced by which group of trees?',
 '[{"id": "a", "text": "Gymnosperms"}, {"id": "b", "text": "Angiosperms"}, {"id": "c", "text": "Monocots"}, {"id": "d", "text": "Pteridophytes"}]'::jsonb, 'a'),
('wsf-104', 'Wood Science & Forest Products', 'Easy', 'practice',
 'The thin layer of dividing cells responsible for diameter growth in a tree is the:',
 '[{"id": "a", "text": "Phloem"}, {"id": "b", "text": "Pith"}, {"id": "c", "text": "Periderm"}, {"id": "d", "text": "Vascular cambium"}]'::jsonb, 'd'),
('wsf-105', 'Wood Science & Forest Products', 'Easy', 'mock',
 'Plywood is manufactured by bonding veneers with the grain of adjacent plies:',
 '[{"id": "a", "text": "Parallel to one another"}, {"id": "b", "text": "At 45 degrees to one another"}, {"id": "c", "text": "In random orientation"}, {"id": "d", "text": "At right angles to one another"}]'::jsonb, 'd'),
('wsf-106', 'Wood Science & Forest Products', 'Easy', 'mock',
 'The principal purpose of seasoning lumber is to:',
 '[{"id": "a", "text": "Reduce moisture content to improve stability and strength"}, {"id": "b", "text": "Increase its moisture content"}, {"id": "c", "text": "Darken its colour"}, {"id": "d", "text": "Remove the bark"}]'::jsonb, 'a'),
('wsf-107', 'Wood Science & Forest Products', 'Easy', 'mock',
 'Which chemical component gives wood cell walls their rigidity and accounts for roughly a quarter of wood substance?',
 '[{"id": "a", "text": "Cellulose"}, {"id": "b", "text": "Starch"}, {"id": "c", "text": "Lignin"}, {"id": "d", "text": "Pectin"}]'::jsonb, 'c'),
('wsf-108', 'Wood Science & Forest Products', 'Easy', 'mock',
 'Sapwood differs from heartwood chiefly in that sapwood:',
 '[{"id": "a", "text": "Contains living parenchyma and conducts sap"}, {"id": "b", "text": "Is always denser"}, {"id": "c", "text": "Is more resistant to decay"}, {"id": "d", "text": "Contains no water"}]'::jsonb, 'a'),
('wsf-109', 'Wood Science & Forest Products', 'Easy', 'mock',
 'Veneer used in plywood manufacture is most commonly produced by:',
 '[{"id": "a", "text": "Rotary peeling of a log against a knife"}, {"id": "b", "text": "Band sawing thin boards"}, {"id": "c", "text": "Extrusion of wood pulp"}, {"id": "d", "text": "Splitting along the rays"}]'::jsonb, 'a'),
('wsf-110', 'Wood Science & Forest Products', 'Easy', 'mock',
 'Which Philippine timber is traditionally prized for its hardness and durability in heavy construction?',
 '[{"id": "a", "text": "Gmelina"}, {"id": "b", "text": "Falcata"}, {"id": "c", "text": "Rubberwood"}, {"id": "d", "text": "Yakal"}]'::jsonb, 'd'),

-- Medium ----------------------------------------------------------------------
('wsf-111', 'Wood Science & Forest Products', 'Medium', 'practice',
 'A wood sample weighs 200 grams green and 125 grams oven-dry. What is its moisture content on the oven-dry basis?',
 '[{"id": "a", "text": "37.5 percent"}, {"id": "b", "text": "60 percent"}, {"id": "c", "text": "75 percent"}, {"id": "d", "text": "160 percent"}]'::jsonb, 'b'),
('wsf-112', 'Wood Science & Forest Products', 'Medium', 'practice',
 'Wood shrinkage is greatest in which direction?',
 '[{"id": "a", "text": "Tangential"}, {"id": "b", "text": "Longitudinal"}, {"id": "c", "text": "Radial"}, {"id": "d", "text": "Shrinkage is equal in all directions"}]'::jsonb, 'a'),
('wsf-113', 'Wood Science & Forest Products', 'Medium', 'practice',
 'Below the fibre saturation point, a decrease in moisture content generally causes wood strength to:',
 '[{"id": "a", "text": "Increase"}, {"id": "b", "text": "Decrease"}, {"id": "c", "text": "Remain unchanged"}, {"id": "d", "text": "Fluctuate randomly"}]'::jsonb, 'a'),
('wsf-114', 'Wood Science & Forest Products', 'Medium', 'practice',
 'The kraft process for pulping wood uses which principal chemicals?',
 '[{"id": "a", "text": "Calcium bisulphite and sulphurous acid"}, {"id": "b", "text": "Hydrogen peroxide and ozone"}, {"id": "c", "text": "Nitric acid and urea"}, {"id": "d", "text": "Sodium hydroxide and sodium sulphide"}]'::jsonb, 'd'),
('wsf-115', 'Wood Science & Forest Products', 'Medium', 'mock',
 'Specific gravity of wood is the ratio of its oven-dry weight to the weight of:',
 '[{"id": "a", "text": "An equal volume of air"}, {"id": "b", "text": "An equal volume of water"}, {"id": "c", "text": "Its green weight"}, {"id": "d", "text": "An equal weight of water"}]'::jsonb, 'b'),
('wsf-116', 'Wood Science & Forest Products', 'Medium', 'mock',
 'Modulus of rupture measures a wood specimen resistance to:',
 '[{"id": "a", "text": "Compression parallel to grain"}, {"id": "b", "text": "Bending failure"}, {"id": "c", "text": "Surface indentation"}, {"id": "d", "text": "Moisture absorption"}]'::jsonb, 'b'),
('wsf-117', 'Wood Science & Forest Products', 'Medium', 'mock',
 'Cupping and warping in drying lumber arise mainly from:',
 '[{"id": "a", "text": "Uniform shrinkage in all directions"}, {"id": "b", "text": "Longitudinal shrinkage exceeding tangential"}, {"id": "c", "text": "Absorption of preservative"}, {"id": "d", "text": "The difference between tangential and radial shrinkage"}]'::jsonb, 'd'),
('wsf-118', 'Wood Science & Forest Products', 'Medium', 'mock',
 'Pressure treatment with preservatives is most effective in which portion of a timber?',
 '[{"id": "a", "text": "Heartwood"}, {"id": "b", "text": "Pith"}, {"id": "c", "text": "Bark"}, {"id": "d", "text": "Sapwood"}]'::jsonb, 'd'),
('wsf-119', 'Wood Science & Forest Products', 'Medium', 'mock',
 'Equilibrium moisture content of wood is determined chiefly by the surrounding air:',
 '[{"id": "a", "text": "Barometric pressure alone"}, {"id": "b", "text": "Carbon dioxide concentration"}, {"id": "c", "text": "Wind speed"}, {"id": "d", "text": "Relative humidity and temperature"}]'::jsonb, 'd'),
('wsf-120', 'Wood Science & Forest Products', 'Medium', 'mock',
 'A block of wood measuring 10 by 10 by 10 centimetres weighs 450 grams oven-dry. Its specific gravity is closest to:',
 '[{"id": "a", "text": "0.045"}, {"id": "b", "text": "0.45"}, {"id": "c", "text": "4.5"}, {"id": "d", "text": "45"}]'::jsonb, 'b'),

-- Hard ------------------------------------------------------------------------
('wsf-121', 'Wood Science & Forest Products', 'Hard', 'practice',
 'The ratio of tangential to radial shrinkage in most timbers is approximately:',
 '[{"id": "a", "text": "2 to 1"}, {"id": "b", "text": "1 to 1"}, {"id": "c", "text": "5 to 1"}, {"id": "d", "text": "10 to 1"}]'::jsonb, 'a'),
('wsf-122', 'Wood Science & Forest Products', 'Hard', 'practice',
 'Quarter-sawn lumber is more dimensionally stable in width than flat-sawn lumber because its wide face is oriented:',
 '[{"id": "a", "text": "Tangential to the growth rings"}, {"id": "b", "text": "Along the longitudinal axis"}, {"id": "c", "text": "At 45 degrees to the rings"}, {"id": "d", "text": "Radially, so width change follows the smaller radial shrinkage"}]'::jsonb, 'd'),
('wsf-123', 'Wood Science & Forest Products', 'Hard', 'practice',
 'Collapse in kiln-dried timber is caused primarily by:',
 '[{"id": "a", "text": "Fungal decay of the cell wall"}, {"id": "b", "text": "Liquid tension in cell lumens during rapid drying above fibre saturation"}, {"id": "c", "text": "Excessive preservative retention"}, {"id": "d", "text": "Slow drying below equilibrium moisture content"}]'::jsonb, 'b'),
('wsf-124', 'Wood Science & Forest Products', 'Hard', 'practice',
 'In wood chemistry, hemicelluloses differ from cellulose principally in being:',
 '[{"id": "a", "text": "Highly crystalline and made of a single sugar"}, {"id": "b", "text": "Aromatic polymers of phenylpropane units"}, {"id": "c", "text": "Inorganic mineral deposits"}, {"id": "d", "text": "Branched, amorphous and composed of several sugar units"}]'::jsonb, 'd'),
('wsf-125', 'Wood Science & Forest Products', 'Hard', 'mock',
 'Preservative retention in treated wood is normally expressed in:',
 '[{"id": "a", "text": "Percent of oven-dry weight"}, {"id": "b", "text": "Millimetres of penetration only"}, {"id": "c", "text": "Litres per linear metre"}, {"id": "d", "text": "Kilograms per cubic metre of wood"}]'::jsonb, 'd'),
('wsf-126', 'Wood Science & Forest Products', 'Hard', 'mock',
 'Reaction wood formed on the lower side of leaning conifer stems is called:',
 '[{"id": "a", "text": "Compression wood"}, {"id": "b", "text": "Tension wood"}, {"id": "c", "text": "Juvenile wood"}, {"id": "d", "text": "Included sapwood"}]'::jsonb, 'a'),
('wsf-127', 'Wood Science & Forest Products', 'Hard', 'mock',
 'Juvenile wood near the pith is generally undesirable for structural use because it has:',
 '[{"id": "a", "text": "Shorter fibres, lower density and higher longitudinal shrinkage"}, {"id": "b", "text": "Greater density and stiffness"}, {"id": "c", "text": "Higher natural decay resistance"}, {"id": "d", "text": "Lower moisture content when green"}]'::jsonb, 'a'),
('wsf-128', 'Wood Science & Forest Products', 'Hard', 'mock',
 'Medium density fibreboard differs from particleboard chiefly in that MDF is made from:',
 '[{"id": "a", "text": "Refined wood fibres rather than wood particles or flakes"}, {"id": "b", "text": "Thin rotary-peeled veneers"}, {"id": "c", "text": "Solid sawn strips glued edgewise"}, {"id": "d", "text": "Chemically pulped paper sheets"}]'::jsonb, 'a'),
('wsf-129', 'Wood Science & Forest Products', 'Hard', 'mock',
 'A timber with specific gravity 0.60 at 12 percent moisture content has an approximate density of:',
 '[{"id": "a", "text": "60 kilograms per cubic metre"}, {"id": "b", "text": "600 kilograms per cubic metre"}, {"id": "c", "text": "1,200 kilograms per cubic metre"}, {"id": "d", "text": "6,000 kilograms per cubic metre"}]'::jsonb, 'b'),
('wsf-130', 'Wood Science & Forest Products', 'Hard', 'mock',
 'Brown rot fungi degrade wood mainly by attacking:',
 '[{"id": "a", "text": "Lignin only"}, {"id": "b", "text": "Extractives in the heartwood"}, {"id": "c", "text": "Cellulose and hemicellulose, leaving lignin largely intact"}, {"id": "d", "text": "Mineral inclusions in the cell wall"}]'::jsonb, 'c'),

-- ============================================================================
-- SOCIAL FORESTRY & FOREST POLICY
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('sfp-101', 'Social Forestry & Forest Policy', 'Easy', 'practice',
 'Presidential Decree No. 705 is otherwise known as the:',
 '[{"id": "a", "text": "NIPAS Act"}, {"id": "b", "text": "Indigenous Peoples Rights Act"}, {"id": "c", "text": "Revised Forestry Code of the Philippines"}, {"id": "d", "text": "Wildlife Resources Conservation and Protection Act"}]'::jsonb, 'c'),
('sfp-102', 'Social Forestry & Forest Policy', 'Easy', 'practice',
 'Under PD 705, lands of the public domain with a slope of what percent or more may not be classified as alienable and disposable?',
 '[{"id": "a", "text": "8 percent"}, {"id": "b", "text": "18 percent"}, {"id": "c", "text": "25 percent"}, {"id": "d", "text": "50 percent"}]'::jsonb, 'b'),
('sfp-103', 'Social Forestry & Forest Policy', 'Easy', 'practice',
 'CBFMA stands for:',
 '[{"id": "a", "text": "Community-Based Forest Management Agreement"}, {"id": "b", "text": "Communal Bureau of Forest Management Authority"}, {"id": "c", "text": "Certified Board of Forest Management Assessment"}, {"id": "d", "text": "Coastal and Bay Forest Management Area"}]'::jsonb, 'a'),
('sfp-104', 'Social Forestry & Forest Policy', 'Easy', 'practice',
 'Republic Act No. 8371 is known as the:',
 '[{"id": "a", "text": "Indigenous Peoples Rights Act"}, {"id": "b", "text": "Clean Air Act"}, {"id": "c", "text": "Agriculture and Fisheries Modernization Act"}, {"id": "d", "text": "Local Government Code"}]'::jsonb, 'a'),
('sfp-105', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'The NIPAS Act, Republic Act No. 7586, established a system for the management of:',
 '[{"id": "a", "text": "Timber licence agreements"}, {"id": "b", "text": "Mineral reservations"}, {"id": "c", "text": "Protected areas"}, {"id": "d", "text": "Agrarian reform beneficiaries"}]'::jsonb, 'c'),
('sfp-106', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'Republic Act No. 9147 governs the conservation and protection of:',
 '[{"id": "a", "text": "Coastal fisheries only"}, {"id": "b", "text": "Mineral resources"}, {"id": "c", "text": "Wildlife resources and their habitats"}, {"id": "d", "text": "Watershed reservations only"}]'::jsonb, 'c'),
('sfp-107', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'A Certificate of Ancestral Domain Title is issued under the authority of which body?',
 '[{"id": "a", "text": "Forest Management Bureau"}, {"id": "b", "text": "Land Registration Authority"}, {"id": "c", "text": "National Commission on Indigenous Peoples"}, {"id": "d", "text": "Department of Agrarian Reform"}]'::jsonb, 'c'),
('sfp-108', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'Social forestry programmes are distinguished chiefly by their emphasis on:',
 '[{"id": "a", "text": "Maximum timber extraction by concessionaires"}, {"id": "b", "text": "Local community participation in forest management and benefit sharing"}, {"id": "c", "text": "Strict exclusion of people from forest lands"}, {"id": "d", "text": "Export-oriented plantation development"}]'::jsonb, 'b'),
('sfp-109', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'Agroforestry is best described as a land-use system that deliberately combines:',
 '[{"id": "a", "text": "Only fast-growing exotic tree species"}, {"id": "b", "text": "Timber harvesting with mining operations"}, {"id": "c", "text": "Woody perennials with crops or livestock on the same unit of land"}, {"id": "d", "text": "Protected areas with urban development"}]'::jsonb, 'c'),
('sfp-110', 'Social Forestry & Forest Policy', 'Easy', 'mock',
 'The bureau under the DENR with primary responsibility for forest policy and programme formulation is the:',
 '[{"id": "a", "text": "Environmental Management Bureau"}, {"id": "b", "text": "Mines and Geosciences Bureau"}, {"id": "c", "text": "Forest Management Bureau"}, {"id": "d", "text": "Biodiversity Management Bureau"}]'::jsonb, 'c'),

-- Medium ----------------------------------------------------------------------
('sfp-111', 'Social Forestry & Forest Policy', 'Medium', 'practice',
 'A Community-Based Forest Management Agreement has a term of:',
 '[{"id": "a", "text": "10 years, non-renewable"}, {"id": "b", "text": "50 years, non-renewable"}, {"id": "c", "text": "25 years, renewable for another 25 years"}, {"id": "d", "text": "Perpetual, subject to annual review"}]'::jsonb, 'c'),
('sfp-112', 'Social Forestry & Forest Policy', 'Medium', 'practice',
 'Executive Order No. 263, series of 1995, adopted which approach as the national strategy for sustainable forestry?',
 '[{"id": "a", "text": "Community-based forest management"}, {"id": "b", "text": "Industrial forest plantation development"}, {"id": "c", "text": "Total log ban"}, {"id": "d", "text": "Selective logging by concessionaires"}]'::jsonb, 'a'),
('sfp-113', 'Social Forestry & Forest Policy', 'Medium', 'practice',
 'Executive Order No. 23, series of 2011, declared a moratorium on:',
 '[{"id": "a", "text": "All mining operations nationwide"}, {"id": "b", "text": "Cutting and harvesting of timber in natural and residual forests"}, {"id": "c", "text": "Issuance of ancestral domain titles"}, {"id": "d", "text": "Establishment of new protected areas"}]'::jsonb, 'b'),
('sfp-114', 'Social Forestry & Forest Policy', 'Medium', 'practice',
 'Free and Prior Informed Consent under IPRA requires that a project affecting ancestral domain:',
 '[{"id": "a", "text": "Be approved solely by the local government unit"}, {"id": "b", "text": "Notify the community only after commencement"}, {"id": "c", "text": "Be cleared by the Forest Management Bureau alone"}, {"id": "d", "text": "Obtain the consent of the affected indigenous community before proceeding"}]'::jsonb, 'd'),
('sfp-115', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'An Integrated Forest Management Agreement is a production-sharing tenure instrument covering:',
 '[{"id": "a", "text": "Development, management and protection of a defined forest land area"}, {"id": "b", "text": "Strict protection zones within national parks"}, {"id": "c", "text": "Mineral extraction in watershed reservations"}, {"id": "d", "text": "Urban greening projects"}]'::jsonb, 'a'),
('sfp-116', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'Republic Act No. 11038 is the law that:',
 '[{"id": "a", "text": "Expanded and strengthened the NIPAS Act"}, {"id": "b", "text": "Created the Department of Environment and Natural Resources"}, {"id": "c", "text": "Established the Philippine Mining Act"}, {"id": "d", "text": "Enacted the Revised Forestry Code"}]'::jsonb, 'a'),
('sfp-117', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'Under PD 705, cutting is generally prohibited on slopes exceeding:',
 '[{"id": "a", "text": "18 percent"}, {"id": "b", "text": "25 percent"}, {"id": "c", "text": "50 percent"}, {"id": "d", "text": "75 percent"}]'::jsonb, 'c'),
('sfp-118', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'A Protected Area Management Board under NIPAS is chaired by the:',
 '[{"id": "a", "text": "DENR Regional Executive Director or authorised representative"}, {"id": "b", "text": "Provincial Governor"}, {"id": "c", "text": "Municipal Mayor"}, {"id": "d", "text": "Barangay Captain"}]'::jsonb, 'a'),
('sfp-119', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'A Socialized Industrial Forest Management Agreement is intended primarily for:',
 '[{"id": "a", "text": "Large corporate concessionaires"}, {"id": "b", "text": "Foreign investors only"}, {"id": "c", "text": "Individuals and families developing small areas of forest land"}, {"id": "d", "text": "Local government units"}]'::jsonb, 'c'),
('sfp-120', 'Social Forestry & Forest Policy', 'Medium', 'mock',
 'The buffer zone surrounding a strict protection zone in a protected area is intended to:',
 '[{"id": "a", "text": "Serve as the core habitat for endangered species"}, {"id": "b", "text": "Be converted to agricultural land"}, {"id": "c", "text": "Absorb pressure and allow regulated multiple use"}, {"id": "d", "text": "Remain permanently closed to all human presence"}]'::jsonb, 'c'),

-- Hard ------------------------------------------------------------------------
('sfp-121', 'Social Forestry & Forest Policy', 'Hard', 'practice',
 'Under the Regalian Doctrine as applied in Philippine forestry law, all lands of the public domain:',
 '[{"id": "a", "text": "Belong to the State unless shown to have been alienated"}, {"id": "b", "text": "Are presumed private unless the State proves otherwise"}, {"id": "c", "text": "Belong to the local government unit where they lie"}, {"id": "d", "text": "Are automatically covered by ancestral domain claims"}]'::jsonb, 'a'),
('sfp-122', 'Social Forestry & Forest Policy', 'Hard', 'practice',
 'The classification of public lands into forest land or alienable and disposable land is an act that may be performed by:',
 '[{"id": "a", "text": "Any Regional Trial Court"}, {"id": "b", "text": "The barangay assembly"}, {"id": "c", "text": "A private surveyor"}, {"id": "d", "text": "The Executive branch, through the President upon DENR recommendation"}]'::jsonb, 'd'),
('sfp-123', 'Social Forestry & Forest Policy', 'Hard', 'practice',
 'Payments for ecosystem services schemes in watershed management are founded on the principle that:',
 '[{"id": "a", "text": "Government alone should finance watershed protection"}, {"id": "b", "text": "Downstream beneficiaries compensate upstream managers for maintaining service flows"}, {"id": "c", "text": "Timber revenue should fund all conservation"}, {"id": "d", "text": "Ecosystem services have no measurable economic value"}]'::jsonb, 'b'),
('sfp-124', 'Social Forestry & Forest Policy', 'Hard', 'practice',
 'REDD-plus mechanisms are designed principally to provide incentives for:',
 '[{"id": "a", "text": "Expanding industrial logging concessions"}, {"id": "b", "text": "Converting forests to biofuel plantations"}, {"id": "c", "text": "Relocating forest-dependent communities"}, {"id": "d", "text": "Reducing emissions from deforestation and forest degradation in developing countries"}]'::jsonb, 'd'),
('sfp-125', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'Tenurial security is regarded as central to community-based forest management because it:',
 '[{"id": "a", "text": "Transfers ownership of the land itself to the community"}, {"id": "b", "text": "Removes all regulatory oversight"}, {"id": "c", "text": "Guarantees a fixed annual government subsidy"}, {"id": "d", "text": "Gives communities a long enough horizon to justify investment in the resource"}]'::jsonb, 'd'),
('sfp-126', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'A Community Resource Management Framework prepared by a CBFMA holder principally sets out:',
 '[{"id": "a", "text": "The annual budget of the DENR regional office"}, {"id": "b", "text": "The boundaries of adjacent mining claims"}, {"id": "c", "text": "The list of protected species nationwide"}, {"id": "d", "text": "The long-term plan for use, protection and development of the awarded area"}]'::jsonb, 'd'),
('sfp-127', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'Where an ancestral domain claim overlaps a declared protected area, prevailing policy calls for:',
 '[{"id": "a", "text": "Automatic cancellation of the ancestral domain claim"}, {"id": "b", "text": "Automatic revocation of the protected area status"}, {"id": "c", "text": "Transfer of jurisdiction to the private sector"}, {"id": "d", "text": "Recognition of both, managed through consultation and co-management arrangements"}]'::jsonb, 'd'),
('sfp-128', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'Devolution of certain forest management functions to local government units was mandated principally by the:',
 '[{"id": "a", "text": "Revised Forestry Code of 1975"}, {"id": "b", "text": "Local Government Code of 1991"}, {"id": "c", "text": "NIPAS Act of 1992"}, {"id": "d", "text": "Wildlife Act of 2001"}]'::jsonb, 'b'),
('sfp-129', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'The chief criticism of the total commercial log ban approach is that, without complementary measures, it tends to:',
 '[{"id": "a", "text": "Immediately restore old-growth forest cover"}, {"id": "b", "text": "Increase government revenue from forest charges"}, {"id": "c", "text": "Eliminate the need for forest protection personnel"}, {"id": "d", "text": "Shift demand to illegal sources and imports rather than reduce consumption"}]'::jsonb, 'd'),
('sfp-130', 'Social Forestry & Forest Policy', 'Hard', 'mock',
 'An Environmental Compliance Certificate is issued following which process?',
 '[{"id": "a", "text": "Cadastral survey of the project site"}, {"id": "b", "text": "Forest inventory of the concession"}, {"id": "c", "text": "Free and Prior Informed Consent alone"}, {"id": "d", "text": "Environmental Impact Assessment under the Philippine EIS System"}]'::jsonb, 'd'),

-- ============================================================================
-- FOREST BIOMETRICS & MENSURATION
-- ============================================================================

-- Easy ------------------------------------------------------------------------
('fbm-101', 'Forest Biometrics & Mensuration', 'Easy', 'practice',
 'Diameter at breast height is conventionally measured at what height above ground?',
 '[{"id": "a", "text": "1.0 metre"}, {"id": "b", "text": "1.3 metres"}, {"id": "c", "text": "1.5 metres"}, {"id": "d", "text": "2.0 metres"}]'::jsonb, 'b'),
('fbm-102', 'Forest Biometrics & Mensuration', 'Easy', 'practice',
 'Basal area of a tree is the cross-sectional area of its stem measured at:',
 '[{"id": "a", "text": "Ground level"}, {"id": "b", "text": "Half the total height"}, {"id": "c", "text": "The base of the live crown"}, {"id": "d", "text": "Breast height"}]'::jsonb, 'd'),
('fbm-103', 'Forest Biometrics & Mensuration', 'Easy', 'practice',
 'A diameter tape gives diameter directly because it is graduated in units of:',
 '[{"id": "a", "text": "Circumference multiplied by pi"}, {"id": "b", "text": "Radius times two"}, {"id": "c", "text": "Area divided by height"}, {"id": "d", "text": "Circumference divided by pi"}]'::jsonb, 'd'),
('fbm-104', 'Forest Biometrics & Mensuration', 'Easy', 'practice',
 'Merchantable height of a tree is measured from stump height to the:',
 '[{"id": "a", "text": "Very tip of the crown"}, {"id": "b", "text": "First live branch always"}, {"id": "c", "text": "Ground line"}, {"id": "d", "text": "Point where the stem reaches a specified minimum usable diameter"}]'::jsonb, 'd'),
('fbm-105', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'Form factor expresses the ratio of actual stem volume to the volume of a:',
 '[{"id": "a", "text": "Cone of the same base and height"}, {"id": "b", "text": "Sphere of the same diameter"}, {"id": "c", "text": "Cube of the same height"}, {"id": "d", "text": "Cylinder of the same basal area and height"}]'::jsonb, 'd'),
('fbm-106', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'The basal area of a tree 40 centimetres in diameter is closest to:',
 '[{"id": "a", "text": "0.063 square metres"}, {"id": "b", "text": "0.126 square metres"}, {"id": "c", "text": "0.251 square metres"}, {"id": "d", "text": "1.257 square metres"}]'::jsonb, 'b'),
('fbm-107', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'A hypsometer is an instrument used to measure:',
 '[{"id": "a", "text": "Stem diameter"}, {"id": "b", "text": "Bark thickness"}, {"id": "c", "text": "Wood density"}, {"id": "d", "text": "Tree height"}]'::jsonb, 'd'),
('fbm-108', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'An increment borer is used to determine a tree:',
 '[{"id": "a", "text": "Total height"}, {"id": "b", "text": "Crown diameter"}, {"id": "c", "text": "Age and radial growth rate"}, {"id": "d", "text": "Root depth"}]'::jsonb, 'c'),
('fbm-109', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'A circular sample plot of 0.1 hectare has a radius closest to:',
 '[{"id": "a", "text": "11.3 metres"}, {"id": "b", "text": "17.8 metres"}, {"id": "c", "text": "25.2 metres"}, {"id": "d", "text": "31.6 metres"}]'::jsonb, 'b'),
('fbm-110', 'Forest Biometrics & Mensuration', 'Easy', 'mock',
 'Stand density expressed as basal area per hectare is normally reported in:',
 '[{"id": "a", "text": "Cubic metres per hectare"}, {"id": "b", "text": "Stems per hectare"}, {"id": "c", "text": "Square metres per hectare"}, {"id": "d", "text": "Kilograms per hectare"}]'::jsonb, 'c'),

-- Medium ----------------------------------------------------------------------
('fbm-111', 'Forest Biometrics & Mensuration', 'Medium', 'practice',
 'A tree has a DBH of 50 centimetres, a merchantable height of 20 metres and a form factor of 0.5. What is its volume?',
 '[{"id": "a", "text": "0.98 cubic metres"}, {"id": "b", "text": "1.96 cubic metres"}, {"id": "c", "text": "3.93 cubic metres"}, {"id": "d", "text": "5.00 cubic metres"}]'::jsonb, 'b'),
('fbm-112', 'Forest Biometrics & Mensuration', 'Medium', 'practice',
 'Using a wedge prism with a basal area factor of 4, a surveyor tallies 9 in trees at a point. Estimated basal area per hectare is:',
 '[{"id": "a", "text": "2.25 square metres"}, {"id": "b", "text": "4 square metres"}, {"id": "c", "text": "13 square metres"}, {"id": "d", "text": "36 square metres"}]'::jsonb, 'd'),
('fbm-113', 'Forest Biometrics & Mensuration', 'Medium', 'practice',
 'Smalian formula computes log volume as the average of the two end areas multiplied by:',
 '[{"id": "a", "text": "The log length"}, {"id": "b", "text": "The mid-length area"}, {"id": "c", "text": "Pi over four"}, {"id": "d", "text": "The taper rate"}]'::jsonb, 'a'),
('fbm-114', 'Forest Biometrics & Mensuration', 'Medium', 'practice',
 'A log 6 metres long has end areas of 0.20 and 0.10 square metres. Its Smalian volume is:',
 '[{"id": "a", "text": "0.60 cubic metres"}, {"id": "b", "text": "0.90 cubic metres"}, {"id": "c", "text": "1.20 cubic metres"}, {"id": "d", "text": "1.80 cubic metres"}]'::jsonb, 'b'),
('fbm-115', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'Huber formula computes log volume from the:',
 '[{"id": "a", "text": "Average of the two end areas times the length"}, {"id": "b", "text": "Cross-sectional area at mid-length times the length"}, {"id": "c", "text": "Larger end area times the length"}, {"id": "d", "text": "Sum of the end areas divided by six"}]'::jsonb, 'b'),
('fbm-116', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'Quadratic mean diameter is the diameter of the tree having the:',
 '[{"id": "a", "text": "Median diameter of the stand"}, {"id": "b", "text": "Largest diameter in the stand"}, {"id": "c", "text": "Arithmetic mean diameter of the stand"}, {"id": "d", "text": "Mean basal area of the stand"}]'::jsonb, 'd'),
('fbm-117', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'A 0.05-hectare plot contains 15 trees. The corresponding stand density is:',
 '[{"id": "a", "text": "75 trees per hectare"}, {"id": "b", "text": "150 trees per hectare"}, {"id": "c", "text": "300 trees per hectare"}, {"id": "d", "text": "750 trees per hectare"}]'::jsonb, 'c'),
('fbm-118', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'Newton formula for log volume requires measurement of:',
 '[{"id": "a", "text": "The mid-length area only"}, {"id": "b", "text": "The two end areas only"}, {"id": "c", "text": "Both end areas and the mid-length area"}, {"id": "d", "text": "The bark thickness at both ends"}]'::jsonb, 'c'),
('fbm-119', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'The total basal area of a stand with 400 trees per hectare averaging 20 centimetres DBH is closest to:',
 '[{"id": "a", "text": "6.3 square metres per hectare"}, {"id": "b", "text": "12.6 square metres per hectare"}, {"id": "c", "text": "25.1 square metres per hectare"}, {"id": "d", "text": "31.4 square metres per hectare"}]'::jsonb, 'b'),
('fbm-120', 'Forest Biometrics & Mensuration', 'Medium', 'mock',
 'Systematic sampling differs from simple random sampling in that plots are located:',
 '[{"id": "a", "text": "Entirely at the discretion of the cruiser"}, {"id": "b", "text": "Only in the most productive stands"}, {"id": "c", "text": "Along the boundary of the tract"}, {"id": "d", "text": "At fixed intervals on a grid after a random start"}]'::jsonb, 'd'),

-- Hard ------------------------------------------------------------------------
('fbm-121', 'Forest Biometrics & Mensuration', 'Hard', 'practice',
 'In horizontal point sampling, the probability that a tree is selected is proportional to its:',
 '[{"id": "a", "text": "Height"}, {"id": "b", "text": "Basal area"}, {"id": "c", "text": "Distance from the point"}, {"id": "d", "text": "Crown width"}]'::jsonb, 'b'),
('fbm-122', 'Forest Biometrics & Mensuration', 'Hard', 'practice',
 'The coefficient of variation of a sample is defined as the:',
 '[{"id": "a", "text": "Standard deviation expressed as a percentage of the mean"}, {"id": "b", "text": "Variance divided by the sample size"}, {"id": "c", "text": "Range divided by the median"}, {"id": "d", "text": "Standard error multiplied by the mean"}]'::jsonb, 'a'),
('fbm-123', 'Forest Biometrics & Mensuration', 'Hard', 'practice',
 'To halve the standard error of an inventory estimate, the sample size must be increased by a factor of approximately:',
 '[{"id": "a", "text": "2"}, {"id": "b", "text": "8"}, {"id": "c", "text": "4"}, {"id": "d", "text": "16"}]'::jsonb, 'c'),
('fbm-124', 'Forest Biometrics & Mensuration', 'Hard', 'practice',
 'A local volume table differs from a standard volume table in that it requires:',
 '[{"id": "a", "text": "Diameter only, height being implied by local conditions"}, {"id": "b", "text": "Both diameter and height"}, {"id": "c", "text": "Diameter, height and form factor"}, {"id": "d", "text": "Age and site index"}]'::jsonb, 'a'),
('fbm-125', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'A stand has a basal area of 28 square metres per hectare and a quadratic mean diameter of 30 centimetres. The number of trees per hectare is closest to:',
 '[{"id": "a", "text": "198"}, {"id": "b", "text": "99"}, {"id": "c", "text": "792"}, {"id": "d", "text": "396"}]'::jsonb, 'd'),
('fbm-126', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'In a wedge prism cruise, a borderline tree should be:',
 '[{"id": "a", "text": "Measured precisely and counted as half if it is exactly borderline"}, {"id": "b", "text": "Always counted as in"}, {"id": "c", "text": "Always counted as out"}, {"id": "d", "text": "Ignored entirely"}]'::jsonb, 'a'),
('fbm-127', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'A taper function describes the change in stem diameter as a function of:',
 '[{"id": "a", "text": "Stand age only"}, {"id": "b", "text": "Site index only"}, {"id": "c", "text": "Crown ratio"}, {"id": "d", "text": "Height along the stem"}]'::jsonb, 'd'),
('fbm-128', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'Stratified random sampling improves inventory precision principally by:',
 '[{"id": "a", "text": "Reducing variance within relatively homogeneous strata"}, {"id": "b", "text": "Increasing the total number of plots required"}, {"id": "c", "text": "Eliminating the need for random selection"}, {"id": "d", "text": "Measuring only the largest trees"}]'::jsonb, 'a'),
('fbm-129', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'In a volume equation of the form V equals a plus b times D squared times H, the term D squared times H is known as the:',
 '[{"id": "a", "text": "Combined variable"}, {"id": "b", "text": "Form quotient"}, {"id": "c", "text": "Taper coefficient"}, {"id": "d", "text": "Site index"}]'::jsonb, 'a'),
('fbm-130', 'Forest Biometrics & Mensuration', 'Hard', 'mock',
 'Continuous forest inventory using permanent sample plots is preferred over successive independent inventories because it:',
 '[{"id": "a", "text": "Estimates change with greater precision by remeasuring the same units"}, {"id": "b", "text": "Requires fewer field crews in the first year"}, {"id": "c", "text": "Eliminates the need for growth models"}, {"id": "d", "text": "Avoids the need to mark plot centres"}]'::jsonb, 'a')

on conflict (id) do update set
  subject           = excluded.subject,
  difficulty        = excluded.difficulty,
  pool              = excluded.pool,
  question          = excluded.question,
  options           = excluded.options,
  correct_answer_id = excluded.correct_answer_id,
  updated_at        = now();
-- explanation is deliberately absent from the update list: re-running this file
-- refreshes wording without discarding an explanation already generated.

-- ----------------------------------------------------------------------------
-- Verification — expect 180 rows, 30 per subject, 60 per difficulty,
-- 72 practice and 108 mock.
-- ----------------------------------------------------------------------------
select pool, difficulty, count(*) as questions
from public.questions
where id ~ '^[a-z]{3}-1[0-3][0-9]$'
group by rollup (pool, difficulty)
order by pool, difficulty;
